striker_1__blow_rank_11 = class ({})
striker_1__blow_rank_12 = class ({})
striker_1__blow_rank_21 = class ({})
striker_1__blow_rank_22 = class ({})
striker_1__blow_rank_31 = class ({})
striker_1__blow_rank_32 = class ({})
striker_1__blow_rank_41 = class ({})
striker_1__blow_rank_42 = class ({})

striker_2__shield_rank_11 = class ({})
striker_2__shield_rank_12 = class ({})
striker_2__shield_rank_21 = class ({})
striker_2__shield_rank_22 = class ({})
striker_2__shield_rank_31 = class ({})
striker_2__shield_rank_32 = class ({})
striker_2__shield_rank_41 = class ({})
striker_2__shield_rank_42 = class ({})

striker_3__portal_rank_11 = class ({})
striker_3__portal_rank_12 = class ({})
striker_3__portal_rank_21 = class ({})
striker_3__portal_rank_22 = class ({})
striker_3__portal_rank_31 = class ({})
striker_3__portal_rank_32 = class ({})
striker_3__portal_rank_41 = class ({})
striker_3__portal_rank_42 = class ({})

striker_4__hammer_rank_11 = class ({})
striker_4__hammer_rank_12 = class ({})
striker_4__hammer_rank_21 = class ({})
striker_4__hammer_rank_22 = class ({})
striker_4__hammer_rank_31 = class ({})
striker_4__hammer_rank_32 = class ({})
striker_4__hammer_rank_41 = class ({})
striker_4__hammer_rank_42 = class ({})

striker_5__sof_rank_11 = class ({})
striker_5__sof_rank_12 = class ({})
striker_5__sof_rank_21 = class ({})
striker_5__sof_rank_22 = class ({})
striker_5__sof_rank_31 = class ({})
striker_5__sof_rank_32 = class ({})
striker_5__sof_rank_41 = class ({})
striker_5__sof_rank_42 = class ({})

striker_u__auto_rank_11 = class ({})
striker_u__auto_rank_12 = class ({})
striker_u__auto_rank_21 = class ({})
striker_u__auto_rank_22 = class ({})
striker_u__auto_rank_31 = class ({})
striker_u__auto_rank_32 = class ({})
striker_u__auto_rank_41 = class ({})
striker_u__auto_rank_42 = class ({})

striker__precache = class ({})
LinkLuaModifier("striker__special_values", "heroes/sun/striker/striker__special_values", LUA_MODIFIER_MOTION_NONE)

function striker__precache:GetIntrinsicModifierName()
    return "striker__special_values"
end

function striker__precache:Spawn()
    if self:IsTrained() == false then self:UpgradeAbility(true) end
end

function striker__precache:Precache(context)
    PrecacheResource("soundfile", "soundevents/soundevent_striker.vsndevts", context)
    PrecacheResource("particle", "particles/econ/events/ti10/blink_dagger_start_ti10_splash.vpcf", context)
    PrecacheResource("particle", "particles/econ/items/phantom_assassin/pa_fall20_immortal_shoulders/pa_fall20_blur_start.vpcf", context)
    PrecacheResource("particle", "particles/econ/events/ti10/blink_dagger_end_ti10_lvl2.vpcf", context)
    PrecacheResource("particle", "particles/econ/items/earthshaker/earthshaker_arcana/earthshaker_arcana_spawn_v2.vpcf", context)
    PrecacheResource("particle", "particles/striker/striker_aftershake.vpcf", context)
    PrecacheResource("particle", "particles/bioshadow/bioshadow_poison_hit_shake.vpcf", context)
    PrecacheResource("particle", "particles/units/heroes/hero_phoenix/phoenix_supernova_radiance.vpcf", context)
    PrecacheResource("particle", "particles/econ/items/ember_spirit/ember_ti9/ember_ti9_flameguard.vpcf", context)
    PrecacheResource("particle", "particles/econ/items/lanaya/ta_ti9_immortal_shoulders/ta_ti9_refraction.vpcf", context)
    PrecacheResource("particle", "particles/units/heroes/hero_oracle/oracle_false_promise_attacked.vpcf", context)
    PrecacheResource("particle", "particles/econ/items/spectre/spectre_arcana/spectre_arcana_radiance_owner_body.vpcf", context)
    PrecacheResource("particle", "particles/econ/events/fall_2021/blink_dagger_fall_2021_end.vpcf", context)
    PrecacheResource("particle", "particles/econ/events/fall_2021/radiance_fall_2021.vpcf", context)
    PrecacheResource("particle", "particles/striker/portal_root/striker_portal_root_cast_tgt.vpcf", context)
    PrecacheResource("particle", "particles/striker/portal_root/striker_portal_root_aoe.vpcf", context)
    PrecacheResource("particle", "particles/striker/portal_root/striker_portal_root_dmg.vpcf", context)
    PrecacheResource("particle", "particles/striker/portal_root/striker_portal_root_purge.vpcf", context)
    PrecacheResource("particle", "particles/striker/portal_purge/striker_portal_purge_hit.vpcf", context)
    PrecacheResource("particle", "particles/striker/portal/striker_portal_ambient.vpcf", context)
    PrecacheResource("particle", "particles/econ/events/ti9/blink_dagger_ti9_end_sparkles_outer.vpcf", context)
    PrecacheResource("particle", "particles/units/heroes/hero_dawnbreaker/dawnbreaker_solar_guardian_aoe.vpcf", context)
    PrecacheResource("particle", "particles/econ/items/omniknight/hammer_ti6_immortal/omniknight_purification_ti6_immortal.vpcf", context)
    PrecacheResource("particle", "particles/econ/items/omniknight/hammer_ti6_immortal/omniknight_purification_immortal_cast.vpcf", context)
    PrecacheResource("particle", "particles/econ/items/axe/axe_ti9_immortal/axe_ti9_gold_call.vpcf", context)
    PrecacheResource("particle", "particles/units/heroes/hero_ogre_magi/ogre_magi_multicast.vpcf", context)
    PrecacheResource("particle", "particles/econ/items/earthshaker/earthshaker_arcana/earthshaker_arcana_blink_start_v2.vpcf", context)
    PrecacheResource("particle", "particles/econ/items/dawnbreaker/dawnbreaker_judgement_of_light/dawnbreaker_judgement_of_light_hammer_projectile.vpcf", context)
    PrecacheResource("particle", "particles/units/heroes/hero_dawnbreaker/dawnbreaker_celestial_hammer_aoe_impact.vpcf", context)
    PrecacheResource("particle", "particles/striker/striker_hammer_grounded.vpcf", context)
    PrecacheResource("particle", "particles/units/heroes/hero_dawnbreaker/dawnbreaker_converge_debuff.vpcf", context)
    PrecacheResource("particle", "particles/striker/ein_sof/striker_ein_sof_illusion.vpcf", context)
    PrecacheResource("particle", "particles/econ/items/dawnbreaker/dawnbreaker_judgement_of_light/dawnbreaker_judgement_of_light_hammer_return.vpcf", context)
    PrecacheResource("particle", "particles/striker/ein_sof/striker_ein_sof_2_buff.vpcf", context)
    PrecacheResource("particle", "particles/striker/ein_sof/striker_ein_sof_buff.vpcf", context)
    PrecacheResource("particle", "particles/econ/items/windrunner/windranger_arcana/windranger_arcana_javelin_tgt_v2.vpcf", context)
    PrecacheResource("particle", "particles/econ/items/dawnbreaker/dawnbreaker_judgement_of_light/dawnbreaker_judgement_of_light_weapon_ambient.vpcf", context)
    PrecacheResource("particle", "particles/econ/items/dawnbreaker/dawnbreaker_judgement_of_light/dawnbreaker_judgement_of_light_head_ambient.vpcf", context)
    PrecacheResource("particle", "particles/econ/items/dawnbreaker/dawnbreaker_judgement_of_light/dawnbreaker_judgement_of_light_armor_ambient.vpcf", context)

    PrecacheResource("model", "models/items/dawnbreaker/judgement_of_light_armor/judgement_of_light_armor.vmdl", context)
    PrecacheResource("model", "models/items/dawnbreaker/judgement_of_light_arms/judgement_of_light_arms.vmdl", context)
    PrecacheResource("model", "models/items/dawnbreaker/judgement_of_light_head/judgement_of_light_head.vmdl", context)
    PrecacheResource("model", "models/items/dawnbreaker/judgment_of_light_weapon/judgment_of_light_weapon.vmdl", context)
end