"Heroes_Team"
{
  "nature"
  {
    "1" "druid"
    "2" "dasdingo"
    "3" "hunter"
  }
  "death"
  {
    "1" "fleaman"
    "2" "bloodstained"
    "3" "lawbreaker"
    "4" "bocuse"
    "5" "vulture"
    "6" "death_slash"
  }
  "sun"
  {
    "1" "baldur"
    "2" "ancient"
    "3" "paladin"
    "4" "templar"
  }
  "moon"
  {
    "1" "icebreaker"
    "2" "genuine"
    "3" "trickster"
    "4" "strider"
  }
}
