baldur_1__power_rank_11 = class ({})
baldur_1__power_rank_12 = class ({})
baldur_1__power_rank_21 = class ({})
baldur_1__power_rank_22 = class ({})
baldur_1__power_rank_31 = class ({})
baldur_1__power_rank_32 = class ({})
baldur_1__power_rank_41 = class ({})
baldur_1__power_rank_42 = class ({})

baldur_2__dash_rank_11 = class ({})
baldur_2__dash_rank_12 = class ({})
baldur_2__dash_rank_21 = class ({})
baldur_2__dash_rank_22 = class ({})
baldur_2__dash_rank_31 = class ({})
baldur_2__dash_rank_32 = class ({})
baldur_2__dash_rank_41 = class ({})
baldur_2__dash_rank_42 = class ({})

baldur_3__barrier_rank_11 = class ({})
baldur_3__barrier_rank_12 = class ({})
baldur_3__barrier_rank_21 = class ({})
baldur_3__barrier_rank_22 = class ({})
baldur_3__barrier_rank_31 = class ({})
baldur_3__barrier_rank_32 = class ({})
baldur_3__barrier_rank_41 = class ({})
baldur_3__barrier_rank_42 = class ({})

baldur_4__rear_rank_11 = class ({})
baldur_4__rear_rank_12 = class ({})
baldur_4__rear_rank_21 = class ({})
baldur_4__rear_rank_22 = class ({})
baldur_4__rear_rank_31 = class ({})
baldur_4__rear_rank_32 = class ({})
baldur_4__rear_rank_41 = class ({})
baldur_4__rear_rank_42 = class ({})

baldur_5__fire_rank_11 = class ({})
baldur_5__fire_rank_12 = class ({})
baldur_5__fire_rank_21 = class ({})
baldur_5__fire_rank_22 = class ({})
baldur_5__fire_rank_31 = class ({})
baldur_5__fire_rank_32 = class ({})
baldur_5__fire_rank_41 = class ({})
baldur_5__fire_rank_42 = class ({})

baldur_u__endurance_rank_11 = class ({})
baldur_u__endurance_rank_12 = class ({})
baldur_u__endurance_rank_21 = class ({})
baldur_u__endurance_rank_22 = class ({})
baldur_u__endurance_rank_31 = class ({})
baldur_u__endurance_rank_32 = class ({})
baldur_u__endurance_rank_41 = class ({})
baldur_u__endurance_rank_42 = class ({})

baldur__precache = class ({})
LinkLuaModifier("baldur_special_values", "heroes/sun/baldur/baldur-special_values", LUA_MODIFIER_MOTION_NONE)

function baldur__precache:GetIntrinsicModifierName()
  return "baldur_special_values"
end

function baldur__precache:Spawn()
	if self:IsTrained() == false then self:UpgradeAbility(true) end
end

function baldur__precache:Precache(context)
  PrecacheResource("model", "models/items/bristleback/bristleback_warrior_of_arena_arms/bristleback_warrior_of_arena_arms.vmdl", context)
  PrecacheResource("model", "models/items/bristleback/bristleback_warrior_of_arena_back/bristleback_warrior_of_arena_back.vmdl", context)
  PrecacheResource("model", "models/items/bristleback/bristleback_warrior_of_arena_head/bristleback_warrior_of_arena_head.vmdl", context)
  PrecacheResource("model", "models/items/bristleback/bristleback_warrior_of_arena_neck/bristleback_warrior_of_arena_neck.vmdl", context)
  PrecacheResource("model", "models/items/bristleback/bristleback_warrior_of_arena_weapon/bristleback_warrior_of_arena_weapon.vmdl", context)

  PrecacheResource("particle", "particles/econ/items/bristleback/bristleback_warrior_of_arena/bristleback_warrior_of_arena_arms.vpcf", context)
  PrecacheResource("particle", "particles/econ/items/bristleback/bristleback_warrior_of_arena/bristleback_warrior_of_arena_back.vpcf", context)
  PrecacheResource("particle", "particles/econ/items/bristleback/bristleback_warrior_of_arena/bristleback_warrior_of_arena_head.vpcf", context)
  PrecacheResource("particle", "particles/econ/items/bristleback/bristleback_warrior_of_arena/bristleback_warrior_of_arena_weapon.vpcf", context)
  PrecacheResource("particle", "particles/bald/bald_inner/bald_inner_owner.vpcf", context)
  PrecacheResource("particle", "particles/units/heroes/hero_bristleback/bristleback_back_dmg.vpcf", context)
  PrecacheResource("particle", "particles/units/heroes/hero_bristleback/bristleback_side_dmg.vpcf", context)
  PrecacheResource("particle", "particles/econ/items/bristleback/bristleback_2022_immortal/bristleback_2022_immortal_lrg_dmg.vpcf", context)
  PrecacheResource("particle", "particles/econ/items/bristleback/bristleback_2022_immortal/bristleback_2022_immortal_side_dmg.vpcf", context)
  PrecacheResource("particle", "particles/units/heroes/hero_dragon_knight/dragon_knight_breathe_fire.vpcf", context)
  PrecacheResource("particle", "particles/econ/items/wraith_king/wraith_king_ti6_bracer/wraith_king_ti6_hellfireblast_debuff.vpcf", context)
  PrecacheResource("particle", "particles/bald/bald_vitality/bald_vitality_status_efx.vpcf", context)
  PrecacheResource("particle", "particles/bald/bald_vitality/bald_vitality_buff.vpcf", context)
  PrecacheResource("particle", "particles/econ/items/spirit_breaker/spirit_breaker_weapon_ti8/spirit_breaker_bash_ti8.vpcf", context)
  PrecacheResource("particle", "particles/bald/bald_dash/bald_dash_timer.vpcf", context)
  PrecacheResource("particle", "particles/bald/bald_dash/bald_dash.vpcf", context)
end