paladin_1__link_rank_11 = class ({})
paladin_1__link_rank_12 = class ({})
paladin_1__link_rank_21 = class ({})
paladin_1__link_rank_22 = class ({})
paladin_1__link_rank_31 = class ({})
paladin_1__link_rank_32 = class ({})
paladin_1__link_rank_41 = class ({})
paladin_1__link_rank_42 = class ({})

paladin_2__shield_rank_11 = class ({})
paladin_2__shield_rank_12 = class ({})
paladin_2__shield_rank_21 = class ({})
paladin_2__shield_rank_22 = class ({})
paladin_2__shield_rank_31 = class ({})
paladin_2__shield_rank_32 = class ({})
paladin_2__shield_rank_41 = class ({})
paladin_2__shield_rank_42 = class ({})

paladin_3__hammer_rank_11 = class ({})
paladin_3__hammer_rank_12 = class ({})
paladin_3__hammer_rank_21 = class ({})
paladin_3__hammer_rank_22 = class ({})
paladin_3__hammer_rank_31 = class ({})
paladin_3__hammer_rank_32 = class ({})
paladin_3__hammer_rank_41 = class ({})
paladin_3__hammer_rank_42 = class ({})

paladin_4__magnus_rank_11 = class ({})
paladin_4__magnus_rank_12 = class ({})
paladin_4__magnus_rank_21 = class ({})
paladin_4__magnus_rank_22 = class ({})
paladin_4__magnus_rank_31 = class ({})
paladin_4__magnus_rank_32 = class ({})
paladin_4__magnus_rank_41 = class ({})
paladin_4__magnus_rank_42 = class ({})

paladin_5__smite_rank_11 = class ({})
paladin_5__smite_rank_12 = class ({})
paladin_5__smite_rank_21 = class ({})
paladin_5__smite_rank_22 = class ({})
paladin_5__smite_rank_31 = class ({})
paladin_5__smite_rank_32 = class ({})
paladin_5__smite_rank_41 = class ({})
paladin_5__smite_rank_42 = class ({})

paladin_u__faith_rank_11 = class ({})
paladin_u__faith_rank_12 = class ({})
paladin_u__faith_rank_21 = class ({})
paladin_u__faith_rank_22 = class ({})
paladin_u__faith_rank_31 = class ({})
paladin_u__faith_rank_32 = class ({})
paladin_u__faith_rank_41 = class ({})
paladin_u__faith_rank_42 = class ({})

paladin__precache = class ({})
LinkLuaModifier("paladin_special_values", "heroes/sun/paladin/paladin-special_values", LUA_MODIFIER_MOTION_NONE)

function paladin__precache:GetIntrinsicModifierName()
  return "paladin_special_values"
end

function paladin__precache:Spawn()
	if self:IsTrained() == false then self:UpgradeAbility(true) end
end

function paladin__precache:Precache(context)
  PrecacheResource("model", "models/items/dawnbreaker/judgement_of_light_armor/judgement_of_light_armor.vmdl", context)
  PrecacheResource("model", "models/items/dawnbreaker/judgement_of_light_arms/judgement_of_light_arms.vmdl", context)
  PrecacheResource("model", "models/items/dawnbreaker/judgement_of_light_head/judgement_of_light_head.vmdl", context)
  PrecacheResource("model", "models/items/dawnbreaker/judgment_of_light_weapon/judgment_of_light_weapon.vmdl", context)

  PrecacheResource("particle", "particles/econ/items/dawnbreaker/dawnbreaker_judgement_of_light/dawnbreaker_judgement_of_light_armor_ambient.vpcf", context)
  PrecacheResource("particle", "particles/paladin/link/paladin_link.vpcf", context)
  PrecacheResource("particle", "particles/econ/items/lanaya/ta_ti9_immortal_shoulders/ta_ti9_refraction.vpcf", context)
  PrecacheResource("particle", "particles/units/heroes/hero_oracle/oracle_false_promise_attacked.vpcf", context)
  PrecacheResource("particle", "particles/econ/items/omniknight/hammer_ti6_immortal/omniknight_purification_ti6_immortal.vpcf", context)
  PrecacheResource("particle", "particles/econ/items/omniknight/hammer_ti6_immortal/omniknight_purification_immortal_cast.vpcf", context)
  PrecacheResource("particle", "particles/econ/items/axe/axe_ti9_immortal/axe_ti9_gold_call.vpcf", context)
  PrecacheResource("particle", "particles/units/heroes/hero_ogre_magi/ogre_magi_multicast.vpcf", context)
  PrecacheResource("particle", "particles/paladin/cross_magnus/paladin_cross_magnus.vpcf", context)
  PrecacheResource("particle", "particles/econ/events/ti10/aegis_lvl_1000_ambient_ti10.vpcf", context)
  PrecacheResource("particle", "particles/items_fx/aegis_respawn_timer.vpcf", context)
  PrecacheResource("particle", "particles/units/heroes/hero_omniknight/omniknight_shard_hammer_of_purity_target.vpcf", context)
  PrecacheResource("particle", "particles/econ/items/earthshaker/earthshaker_arcana/earthshaker_arcana_spawn_v2.vpcf", context)
  PrecacheResource("particle", "particles/bioshadow/bioshadow_poison_hit_shake.vpcf", context)
  PrecacheResource("particle", "particles/units/heroes/hero_omniknight/omniknight_shard_hammer_of_purity_heal.vpcf", context)
end