paladin_1__link_rank_11 = class ({})
paladin_1__link_rank_12 = class ({})
paladin_1__link_rank_21 = class ({})
paladin_1__link_rank_22 = class ({})
paladin_1__link_rank_31 = class ({})
paladin_1__link_rank_32 = class ({})

paladin_2__shield_rank_11 = class ({})
paladin_2__shield_rank_12 = class ({})
paladin_2__shield_rank_21 = class ({})
paladin_2__shield_rank_22 = class ({})
paladin_2__shield_rank_31 = class ({})
paladin_2__shield_rank_32 = class ({})

paladin_3__hammer_rank_11 = class ({})
paladin_3__hammer_rank_12 = class ({})
paladin_3__hammer_rank_21 = class ({})
paladin_3__hammer_rank_22 = class ({})
paladin_3__hammer_rank_31 = class ({})
paladin_3__hammer_rank_32 = class ({})

paladin_4__magnus_rank_11 = class ({})
paladin_4__magnus_rank_12 = class ({})
paladin_4__magnus_rank_21 = class ({})
paladin_4__magnus_rank_22 = class ({})
paladin_4__magnus_rank_31 = class ({})
paladin_4__magnus_rank_32 = class ({})

paladin_5__smite_rank_11 = class ({})
paladin_5__smite_rank_12 = class ({})
paladin_5__smite_rank_21 = class ({})
paladin_5__smite_rank_22 = class ({})
paladin_5__smite_rank_31 = class ({})
paladin_5__smite_rank_32 = class ({})

paladin_u__faith_rank_11 = class ({})
paladin_u__faith_rank_12 = class ({})
paladin_u__faith_rank_21 = class ({})
paladin_u__faith_rank_22 = class ({})
paladin_u__faith_rank_31 = class ({})
paladin_u__faith_rank_32 = class ({})

paladin__precache = class ({})
LinkLuaModifier("paladin_special_values", "heroes/sun/paladin/paladin-special_values", LUA_MODIFIER_MOTION_NONE)

function paladin__precache:GetIntrinsicModifierName()
  return "paladin_special_values"
end

function paladin__precache:Spawn()
	if self:IsTrained() == false then self:UpgradeAbility(true) end
end

function paladin__precache:Precache(context)
  PrecacheResource("model", "models/items/dawnbreaker/judgement_of_light_armor/judgement_of_light_armor.vmdl", context)
  PrecacheResource("model", "models/items/dawnbreaker/judgement_of_light_arms/judgement_of_light_arms.vmdl", context)
  PrecacheResource("model", "models/items/dawnbreaker/judgement_of_light_head/judgement_of_light_head.vmdl", context)
  PrecacheResource("model", "models/items/dawnbreaker/judgment_of_light_weapon/judgment_of_light_weapon.vmdl", context)

  PrecacheResource("particle", "particles/econ/items/dawnbreaker/dawnbreaker_judgement_of_light/dawnbreaker_judgement_of_light_armor_ambient.vpcf", context)
  PrecacheResource("particle", "particles/paladin/link/paladin_link.vpcf", context)
  PrecacheResource("particle", "particles/units/heroes/hero_phoenix/phoenix_supernova_radiance.vpcf", context)
  PrecacheResource("particle", "particles/econ/items/lanaya/ta_ti9_immortal_shoulders/ta_ti9_refraction.vpcf", context)
  PrecacheResource("particle", "particles/econ/items/ember_spirit/ember_ti9/ember_ti9_flameguard.vpcf", context)
  PrecacheResource("particle", "particles/units/heroes/hero_oracle/oracle_false_promise_attacked.vpcf", context)
  PrecacheResource("particle", "particles/econ/items/omniknight/hammer_ti6_immortal/omniknight_purification_ti6_immortal.vpcf", context)
  PrecacheResource("particle", "particles/econ/items/omniknight/hammer_ti6_immortal/omniknight_purification_immortal_cast.vpcf", context)
  PrecacheResource("particle", "particles/econ/items/axe/axe_ti9_immortal/axe_ti9_gold_call.vpcf", context)
  PrecacheResource("particle", "particles/paladin/multi_combo/paladin_multi_combo.vpcf", context)
  PrecacheResource("particle", "particles/econ/events/ti10/blink_dagger_start_ti10_lvl2.vpcf", context)
  PrecacheResource("particle", "particles/econ/events/ti10/blink_dagger_end_ti10_lvl2.vpcf", context)
  PrecacheResource("particle", "particles/units/heroes/hero_omniknight/omniknight_purification_hit.vpcf", context)
  PrecacheResource("particle", "particles/units/heroes/hero_omniknight/omniknight_purification.vpcf", context)
  PrecacheResource("particle", "particles/paladin/cross_magnus/paladin_cross_magnus.vpcf", context)
  PrecacheResource("particle", "particles/units/heroes/hero_omniknight/omniknight_shard_hammer_of_purity_target.vpcf", context)
  PrecacheResource("particle", "particles/econ/items/earthshaker/earthshaker_arcana/earthshaker_arcana_spawn_v2.vpcf", context)
  PrecacheResource("particle", "particles/units/heroes/hero_omniknight/omniknight_shard_hammer_of_purity_heal.vpcf", context)
  PrecacheResource("particle", "particles/econ/events/ti10/blink_dagger_start_ti10_splash.vpcf", context)
  PrecacheResource("particle", "particles/econ/items/phantom_assassin/pa_fall20_immortal_shoulders/pa_fall20_blur_start.vpcf", context)
  PrecacheResource("particle", "particles/paladin/aura_faith/aura_faith.vpcf", context)
  PrecacheResource("particle", "particles/econ/events/fall_2022/mekanism/mekanism_fall2022.vpcf", context)
end