const perks_levels = 3;
const game_perks = [
	`family`,
	`attack_speed`,
	`armor`,
	// `cast_time`,
	`tinkerer`,
	`magician`,
	// `linken`,
	`buff_amplify`,
	// `builder`,
	// `traveler`,
	`delayed_damage`,
	`str_for_kill`,
	`agi_for_kill`,
	`int_for_kill`,
	`cleave`,
	`cd_after_death`,
	`manaburn`,
	`mp_regen`,
	`hp_regen`,
	`bonus_movespeed`,
	`bonus_agi`,
	`bonus_str`,
	`bonus_int`,
	`bonus_all_stats`,
	`attack_range`,
	`bonus_hp_pct`,
	`cast_range`,
	`cooldown_reduction`,
	`damage`,
	`evasion`,
	`lifesteal`,
	`mag_resist`,
	`spell_amp`,
	`spell_lifesteal`,
	`status_resistance`,
	`outcomming_heal_amplify`,
	`debuff_time`,
	`bonus_gold`,
];
