icebreaker_1__frost_rank_11 = class ({})
icebreaker_1__frost_rank_12 = class ({})
icebreaker_1__frost_rank_21 = class ({})
icebreaker_1__frost_rank_22 = class ({})
icebreaker_1__frost_rank_31 = class ({})
icebreaker_1__frost_rank_32 = class ({})
icebreaker_1__frost_rank_41 = class ({})
icebreaker_1__frost_rank_42 = class ({})

icebreaker_2__wave_rank_11 = class ({})
icebreaker_2__wave_rank_12 = class ({})
icebreaker_2__wave_rank_21 = class ({})
icebreaker_2__wave_rank_22 = class ({})
icebreaker_2__wave_rank_31 = class ({})
icebreaker_2__wave_rank_32 = class ({})
icebreaker_2__wave_rank_41 = class ({})
icebreaker_2__wave_rank_42 = class ({})

icebreaker_3__skin_rank_11 = class ({})
icebreaker_3__skin_rank_12 = class ({})
icebreaker_3__skin_rank_21 = class ({})
icebreaker_3__skin_rank_22 = class ({})
icebreaker_3__skin_rank_31 = class ({})
icebreaker_3__skin_rank_32 = class ({})
icebreaker_3__skin_rank_41 = class ({})
icebreaker_3__skin_rank_42 = class ({})

icebreaker_4__shivas_rank_11 = class ({})
icebreaker_4__shivas_rank_12 = class ({})
icebreaker_4__shivas_rank_21 = class ({})
icebreaker_4__shivas_rank_22 = class ({})
icebreaker_4__shivas_rank_31 = class ({})
icebreaker_4__shivas_rank_32 = class ({})
icebreaker_4__shivas_rank_41 = class ({})
icebreaker_4__shivas_rank_42 = class ({})

icebreaker_5__blink_rank_11 = class ({})
icebreaker_5__blink_rank_12 = class ({})
icebreaker_5__blink_rank_21 = class ({})
icebreaker_5__blink_rank_22 = class ({})
icebreaker_5__blink_rank_31 = class ({})
icebreaker_5__blink_rank_32 = class ({})
icebreaker_5__blink_rank_41 = class ({})
icebreaker_5__blink_rank_42 = class ({})

icebreaker_u__zero_rank_11 = class ({})
icebreaker_u__zero_rank_12 = class ({})
icebreaker_u__zero_rank_21 = class ({})
icebreaker_u__zero_rank_22 = class ({})
icebreaker_u__zero_rank_31 = class ({})
icebreaker_u__zero_rank_32 = class ({})
icebreaker_u__zero_rank_41 = class ({})
icebreaker_u__zero_rank_42 = class ({})

icebreaker__precache = class ({})
LinkLuaModifier("icebreaker_special_values", "heroes/moon/icebreaker/icebreaker-special_values", LUA_MODIFIER_MOTION_NONE)

function icebreaker__precache:GetIntrinsicModifierName()
  return "icebreaker_special_values"
end

function icebreaker__precache:Spawn()
	if self:IsTrained() == false then self:UpgradeAbility(true) end
end

function icebreaker__precache:Precache(context)
  PrecacheResource( "particle", "particles/econ/items/drow/drow_ti9_immortal/status_effect_drow_ti9_frost_arrow.vpcf", context )
  PrecacheResource( "particle", "particles/econ/items/winter_wyvern/winter_wyvern_ti7/wyvern_cold_embrace_ti7buff.vpcf", context )
  PrecacheResource( "particle", "particles/units/heroes/hero_winter_wyvern/wyvern_arctic_burn_start.vpcf", context )
  PrecacheResource( "particle", "particles/econ/items/crystal_maiden/crystal_maiden_maiden_of_icewrack/cm_arcana_pup_flee.vpcf", context )
  PrecacheResource( "particle", "particles/units/heroes/hero_abaddon/abaddon_curse_frostmourne_debuff.vpcf", context )
  PrecacheResource( "particle", "particles/units/heroes/hero_drow/drow_hypothermia_counter_stack.vpcf", context )
  PrecacheResource( "particle", "particles/icebreaker/icebreaker_counter_stack.vpcf", context )
  PrecacheResource( "particle", "particles/econ/items/effigies/status_fx_effigies/status_effect_effigy_frosty_l2_radiant.vpcf", context )
  PrecacheResource( "particle", "particles/econ/items/sven/sven_ti7_sword/sven_ti7_sword_spell_great_cleave_crit.vpcf", context )
  PrecacheResource( "particle", "particles/econ/events/winter_major_2017/blink_dagger_start_wm07.vpcf", context )
  PrecacheResource( "particle", "particles/econ/items/effigies/status_fx_effigies/status_effect_effigy_frosty_radiant.vpcf", context )
  PrecacheResource( "particle", "particles/units/heroes/hero_ancient_apparition/ancient_apparition_ambient.vpcf", context )
  PrecacheResource( "particle", "particles/units/heroes/hero_ancient_apparition/ancient_apparition_chilling_touch_buff.vpcf", context )
  PrecacheResource( "particle", "particles/econ/items/drow/drow_arcana/drow_arcana_silence_wave.vpcf", context )
  PrecacheResource( "particle", "particles/units/heroes/hero_lich/lich_ice_age.vpcf", context )
  PrecacheResource( "particle", "particles/units/heroes/hero_lich/lich_frost_armor.vpcf", context )
  PrecacheResource( "particle", "particles/econ/items/ancient_apparition/aa_blast_ti_5/ancient_apparition_ice_blast_explode_ti5.vpcf", context )
  PrecacheResource( "particle", "particles/items2_fx/shivas_guard_active.vpcf", context )
  PrecacheResource( "particle", "particles/items2_fx/shivas_guard_impact.vpcf", context )
  PrecacheResource( "particle", "particles/econ/events/winter_major_2017/blink_dagger_start_wm07.vpcf" , context )
  PrecacheResource( "particle", "particles/econ/events/winter_major_2017/blink_dagger_end_wm07.vpcf", context )
  PrecacheResource( "particle", "particles/units/heroes/hero_phantom_assassin_persona/pa_persona_crit_impact.vpcf", context )
  PrecacheResource( "particle", "particles/econ/items/techies/techies_arcana/techies_suicide_kills_arcana.vpcf", context )
  PrecacheResource( "particle", "particles/units/heroes/hero_tusk/tusk_frozen_sigil.vpcf", context )
  PrecacheResource( "particle", "particles/icebreaker/icebreaker_zero.vpcf", context )
  PrecacheResource( "particle", "particles/units/heroes/hero_crystalmaiden_persona/cm_persona_freezing_field_explosion.vpcf", context )

  PrecacheResource( "model", "models/items/rikimaru/riki_scarlet_fox_arms/riki_scarlet_fox_arms.vmdl", context )
	PrecacheResource( "model", "models/items/rikimaru/riki_scarlet_fox_head/riki_scarlet_fox_head.vmdl", context )
	PrecacheResource( "model", "models/items/rikimaru/riki_scarlet_fox_offhand_weapon/riki_scarlet_fox_offhand_weapon.vmdl", context )
	PrecacheResource( "model", "models/items/rikimaru/riki_scarlet_fox_shoulder/riki_scarlet_fox_shoulder.vmdl", context )
	PrecacheResource( "model", "models/items/rikimaru/riki_scarlet_fox_tail/riki_scarlet_fox_tail.vmdl", context )
	PrecacheResource( "model", "models/items/rikimaru/riki_scarlet_fox_weapon/riki_scarlet_fox_weapon.vmdl", context )
	PrecacheResource( "particle", "particles/econ/items/riki/riki_2022_fox_head/riki_2022_fox_head_ambient.vpcf", context )
	PrecacheResource( "particle", "particles/econ/items/riki/riki_2022_fox_offhand/riki_2022_fox_offhand_ambient.vpcf", context )
	PrecacheResource( "particle", "particles/econ/items/riki/riki_2022_fox_weapon/riki_2022_fox_weapon_ambient.vpcf", context )
end